version: '3'
services:
  client:
    image: jasonwvh/landcover-analytics:client
    ports: 
      - "3000:3000"
    networks: 
      - lc-app
  server:
    image: jasonwvh/landcover-analytics:server
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    ports: 
      - "5000:5000"
    networks: 
      - lc-app
networks:
  lc-app:
    driver: bridge
volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local